- name: Install the latest version of ruff
  uses: astral-sh/ruff-action@v2
  with:
    version: latest
- name: Check with ruff
  uses: astral-sh/ruff-action@v2
  with:
    args: check
- name: Format with ruff
  uses: astral-sh/ruff-action@v2
  with:
    args: format
